name: Branch Check CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install dependencies
      run: make dependencies
    - name: Run lint
      run: make lint
    - name: Run test
      run: make test
      
